hwagain: 
 conf:
    allowedOrigins:
                 - '*'
    attachmentBaseDirectory : ./upload
    defaultLocale: zh_CN
    debugPageResult: false
    recordOperateLog: true
    supportLocales: 
                 - zh_CN 
                 - en_US
    defaultPage: readme.html
    hostPrefix : 
    staticMappings:
         /resource/**: 
                - classpath:/WEB-INF/static/                
         /flowchart/**: 
            - classpath:/WEB-INF/flowchart/
    #rpc不需要增加用户信息方法
    notNeedUserMethods: 
 apiInfo:
       title: HWAGAIN REST API
       description: 
       version: 2.0.0
       termsOfServiceUrl: 
       contact: 
            name: 韩金
            url:   
            email:   
       license: 
       licenseUrl: 
       pathsRegex: ^.*(?<!error)$
 
spring:
   http: 
      multipart: 
          maxFileSize: 5MB
          maxRequestSize: 5MB
   datasource:
             platform: mysql
             url: jdbc:mysql://192.168.68.204:3306/hwagain_order_meal?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
             username: sit
             password: abc-123
             driverClassName: com.mysql.jdbc.Driver
             type: com.alibaba.druid.pool.DruidDataSource
             initialSize: 5
             minIdle: 5
             maxActive: 20
             # 配置获取连接等待超时的时间
             maxWait: 60000
             validationQuery: SELECT 1
             testOnBorrow: false
             testOnReturn: false
             testWhileIdle: true
             minEvictableIdleTimeMillis: 25200000
             # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
             timeBetweenEvictionRunsMillis: 60000
             removeAbandoned: true
             removeAbandonedTimeout: 1800
             # 打开PSCache，并且指定每个连接上PSCache的大小
             poolPreparedStatements: true
             maxPoolPreparedStatementPerConnectionSize: 20
             logAbandoned: true
             # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
             filters: stat,wall,log4j
             useGlobalDataSourceStat: true
             multiStatementAllow: true
   jackson:
          date-format: yyyy-MM-dd HH:mm:ss
          short-date-format: yyyy-MM-dd
          default-property-inclusion: non_null
   thymeleaf: 
       prefix: classpath:/html
       suffix: .html
       cache: false 
   messages:
        basename: i18n/messages 
   redis:
      database: 0
      host: 192.168.68.207
      port: 6379
      password:
      jedis:
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
      timeout: 5000
      ssl: false
      url:
      
   cluster:  
      redis:
         host: 192.168.68.207
         port: 6379
         password: 
         masterName: audit6379
         maxTotal: 200
         maxIdle: 50
         numTestsPerEvictionRun: 1024
         maxWaitMillis: 1500
         type: singleton # singleton:单机 , sentinel:哨兵, cluster:集群
         expire: 1800
         nodes:
             - host: 192.168.68.207
               port: 6379       

server:
    port: 8080
    session: 
        timeout: 30
    context-path: /order-meal-wx
    tomcat:
      uri-encoding: UTF-8
      
logging:
    config: classpath:logback.xml
mybatis: 
   mapperLocations: classpath*:com/hwagain/system/**/mapper/xml/*Mapper.xml 
   typeAliasesPackage: com.hwagain.system.**.entity
shiro:
    conf:
        successUrl: onLoginSuccess
        domain: .hwagain.com
        unauthorizedUrl:
        loginView: /doLogin
        openToken: true
        securityKey: sso_dev_id
        tokenKey: hwagain_sso_token_test
        isUpdatePwd: false
        sysanon: 
              - /anonymous/**
sys:
   config:
      dubbo:
         zookeeper-address: 192.168.68.207:2181
         owner: dev
         provider-version: localdev
         application-version: dev.1.0
         esb-provider-version: dev.1.0
         retries: 0
         port: 60099
         timeout: 50000    
         orgsys-version: dev.1.0
wx:
  mp:
    appId: wx8db035a530970a90
    secret: 5e70a96953bc22cfea41de7713d679cc
    token: 123123123
    #    aesKey: 111 （接口配置里的EncodingAESKey值）
    aesKey: qmpDpN5vpGPnUVGmL7aJY1r32JfWKXKB9xOxeUTe6Yg
    domain: http://888xin.nat300.top/
    #    domain: https://www.hwagain.com/forestry-wechat/
    localDomain: http://192.168.65.123:8086/
    #    localDomain: http://172.16.1.67:80/forestry-wechat/
    foreEnd: http://unclemeric.cn:9000/#/
#    foreEnd: https://www.hwagain.com/forestry-wechat-web/#/
#    foreEndLogin: http://unclemeric.cn:9000/#/login
#    foreEndMain: http://unclemeric.cn:9000/#/apps

